module.exports = {
  env: {
    es2022: true,
    node: true,
  },
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:sonarjs/recommended",
    "plugin:unicorn/all",
    "plugin:prettier/recommended",
  ],
  ignorePatterns: ["node_modules", "build", "dist", "mocks"],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaVersion: "latest",
    project: "tsconfig.json",
    sourceType: "module",
  },
  plugins: [
    "@typescript-eslint",
    "import-helpers",
    "unused-imports",
    "typescript-sort-keys",
    "sonarjs",
    "unicorn",
  ],
  root: true,
  rules: {
    "@typescript-eslint/naming-convention": [
      "off",
      {
        selector: "interface",
        format: ["PascalCase"],
        custom: {
          regex: "^I[A-Z]",
          match: true,
        },
      },
    ],
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-shadow": ["warn"],
    "@typescript-eslint/no-unused-vars": [
      "warn",
      {
        args: "after-used",
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        ignoreRestSiblings: true,
      },
    ],
    "comma-dangle": "off",
    curly: ["warn"],
    "default-param-last": "warn",
    "dot-notation": "warn",
    eqeqeq: "warn",
    "func-name-matching": "warn",
    "import-helpers/order-imports": [
      "warn",
      {
        newlinesBetween: "never",
        groups: ["module", "/^@/", "/^~/", ["parent", "sibling", "index"]],
        alphabetize: {
          order: "asc",
          ignoreCase: true,
        },
      },
    ],
    "max-depth": [
      "warn",
      {
        max: 1,
      },
    ],
    "max-lines": [
      "warn",
      {
        max: 100,
        skipBlankLines: true,
        skipComments: true,
      },
    ],
    "multiline-comment-style": "off",
    "no-else-return": "warn",
    "no-extra-boolean-cast": "warn",
    "no-lonely-if": "warn",
    "no-magic-numbers": [
      "warn",
      {
        enforceConst: true,
        detectObjects: false,
        ignoreArrayIndexes: true,
        ignoreDefaultValues: true,
        ignoreClassFieldInitialValues: true,
        ignore: [-1, 0, 0.5, 1, 2, 3, 100],
      },
    ],
    "no-return-assign": "warn",
    "no-shadow": "off",
    "no-undef": "off",
    "no-unneeded-ternary": "warn",
    "no-useless-return": "warn",
    "padding-line-between-statements": [
      "warn",
      {
        blankLine: "always",
        prev: ["multiline-block-like", "const", "let", "var"],
        next: "*",
      },
      {
        blankLine: "always",
        prev: "*",
        next: ["multiline-block-like", "return", "throw"],
      },
      {
        blankLine: "never",
        prev: ["singleline-const", "singleline-let", "singleline-var"],
        next: ["singleline-const", "singleline-let", "singleline-var"],
      },
      {
        blankLine: "always",
        prev: ["multiline-const", "multiline-let", "multiline-var"],
        next: ["multiline-const", "multiline-let", "multiline-var"],
      },
    ],
    "prefer-template": "warn",
    "prettier/prettier": "off",
    "require-await": "off",
    semi: "off",
    "sonarjs/no-duplicate-string": "warn",
    "sonarjs/no-inverted-boolean-check": "warn",
    "sort-keys": "off",
    "unicorn/custom-error-definition": "off",
    "unicorn/no-keyword-prefix": "off",
    "unicorn/no-nested-ternary": "off",
    "unicorn/no-null": "off",
    "unicorn/no-static-only-class": "off",
    "unicorn/no-useless-undefined": "off",
    "unicorn/numeric-separators-style": "warn",
    "unicorn/prefer-dom-node-dataset": "off",
    "unicorn/prefer-logical-operator-over-ternary": "warn",
    "unicorn/prefer-module": "off",
    "unicorn/prevent-abbreviations": [
      "warn",
      {
        ignore: [
          "\\.prod|dev$",
          "args",
          "env",
          "Env",
          "fn",
          "Fn",
          "lib",
          "Lib",
          "obj",
          "Obj",
          "params",
          "Params",
          "props",
          "Props",
          "Prop",
          "ref",
          "Ref",
          "temp",
          "Temp",
        ],
      },
    ],
    "unused-imports/no-unused-imports-ts": "warn",
    "unused-imports/no-unused-vars": "off",
    "typescript-sort-keys/interface": "off",
    "typescript-sort-keys/string-enum": "warn",
  },
  settings: {
    "import/parsers": {
      [require.resolve("@typescript-eslint/parser")]: [".ts", ".tsx", ".d.ts"],
    },
    "import/resolver": {
      typescript: {
        project: "./tsconfig.json",
      },
    },
  },
};
